"use client";

import { useEffect, useState } from "react";
import { apiFetch } from "@/lib/api";
import Sidebar from "../../components/Sidebar";

type Rule = { id: string; name: string; enabled: boolean };
type Settings = { phone: string; email: string; address: string; website: string; automation_enabled: boolean; default_response: string; human_handoff_message: string; auto_create_leads: boolean; default_lead_status: string; ai_fallback_enabled: boolean; ai_provider: string };
type SettingsResponse = { settings: Partial<Settings> | null };
type Channel = { id: string; business_id: string; name: string; whatsapp_business_account_id: string; phone_number_id: string; graph_api_version: string; active: boolean; created_at: string; updated_at: string };
type ChannelsResponse = { channels: Channel[] };

const defaults: Settings = { phone: "", email: "", address: "", website: "", automation_enabled: true, default_response: "Thanks for contacting Camluk Technologies. We have received your message and will get back to you shortly.", human_handoff_message: "Thanks. I’m connecting you with a member of the Camluk Technologies team.", auto_create_leads: true, default_lead_status: "new", ai_fallback_enabled: false, ai_provider: "" };
function stringValue(value: unknown, fallback = ""): string { return typeof value === "string" ? value : fallback; }
function normalizeSettings(value: Partial<Settings> | null | undefined): Settings { return { phone: stringValue(value?.phone), email: stringValue(value?.email), address: stringValue(value?.address), website: stringValue(value?.website), automation_enabled: typeof value?.automation_enabled === "boolean" ? value.automation_enabled : defaults.automation_enabled, default_response: stringValue(value?.default_response, defaults.default_response), human_handoff_message: stringValue(value?.human_handoff_message, defaults.human_handoff_message), auto_create_leads: typeof value?.auto_create_leads === "boolean" ? value.auto_create_leads : defaults.auto_create_leads, default_lead_status: stringValue(value?.default_lead_status, defaults.default_lead_status), ai_fallback_enabled: typeof value?.ai_fallback_enabled === "boolean" ? value.ai_fallback_enabled : defaults.ai_fallback_enabled, ai_provider: stringValue(value?.ai_provider) }; }
const businessFields: Array<{ label: string; key: keyof Pick<Settings, "phone" | "email" | "website" | "address">; type: string; placeholder: string }> = [
  { label: "Phone", key: "phone", type: "text", placeholder: "Business phone" }, { label: "Email", key: "email", type: "email", placeholder: "Business email" }, { label: "Website", key: "website", type: "url", placeholder: "https://..." }, { label: "Address", key: "address", type: "text", placeholder: "Business address" },
];

export default function SettingsPage() {
  const [settings, setSettings] = useState<Settings>(defaults); const [rules, setRules] = useState<Rule[]>([]); const [channels, setChannels] = useState<Channel[]>([]); const [loading, setLoading] = useState(true); const [channelsLoading, setChannelsLoading] = useState(true); const [saving, setSaving] = useState(false); const [channelSaving, setChannelSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [channelError, setChannelError] = useState(""); const [editingId, setEditingId] = useState<string | null>(null); const [channelForm, setChannelForm] = useState({ name: "", whatsappBusinessAccountId: "", phoneNumberId: "", accessToken: "", verifyToken: "", graphApiVersion: "v23.0" });

  async function loadChannels() { setChannelsLoading(true); setChannelError(""); try { const data = await apiFetch<ChannelsResponse>("/api/whatsapp/channels"); setChannels(data.channels); } catch (err) { setChannelError(err instanceof Error ? err.message : "Failed to load WhatsApp channels."); } finally { setChannelsLoading(false); } }
  useEffect(() => { void (async () => { try { const [settingsData, rulesData] = await Promise.all([apiFetch<SettingsResponse>("/api/settings"), apiFetch<{ rules: Rule[] }>("/api/automation/rules")]); setSettings(normalizeSettings(settingsData.settings)); setRules(rulesData.rules); } catch (err) { setError(err instanceof Error ? err.message : "Failed to load settings."); } finally { setLoading(false); } })(); void loadChannels(); }, []);
  function update<K extends keyof Settings>(key: K, value: Settings[K]) { setSettings((current) => ({ ...current, [key]: value })); setMessage(""); }
  function updateChannel(key: keyof typeof channelForm, value: string) { setChannelForm((current) => ({ ...current, [key]: value })); setChannelError(""); }
  function resetChannelForm() { setEditingId(null); setChannelForm({ name: "", whatsappBusinessAccountId: "", phoneNumberId: "", accessToken: "", verifyToken: "", graphApiVersion: "v23.0" }); }
  function editChannel(channel: Channel) { setEditingId(channel.id); setChannelForm({ name: channel.name, whatsappBusinessAccountId: channel.whatsapp_business_account_id, phoneNumberId: channel.phone_number_id, accessToken: "", verifyToken: "", graphApiVersion: channel.graph_api_version }); setChannelError(""); }
  async function saveSettings() { setSaving(true); setMessage(""); setError(""); try { const data = await apiFetch<SettingsResponse>("/api/settings", { method: "PATCH", body: JSON.stringify(settings) }); setSettings(normalizeSettings(data.settings)); setMessage("Settings saved successfully."); } catch (err) { setError(err instanceof Error ? err.message : "Failed to save settings."); } finally { setSaving(false); } }
  async function saveChannel() { setChannelSaving(true); setChannelError(""); try { if (!editingId && (!channelForm.accessToken.trim() || !channelForm.verifyToken.trim())) throw new Error("Access token and verify token are required when creating a channel."); const body: Record<string, unknown> = { name: channelForm.name, whatsappBusinessAccountId: channelForm.whatsappBusinessAccountId, phoneNumberId: channelForm.phoneNumberId, graphApiVersion: channelForm.graphApiVersion }; if (channelForm.accessToken.trim()) body.accessToken = channelForm.accessToken; if (channelForm.verifyToken.trim()) body.verifyToken = channelForm.verifyToken; const data = await apiFetch<{ channel: Channel }>(editingId ? `/api/whatsapp/channels/${editingId}` : "/api/whatsapp/channels", { method: editingId ? "PATCH" : "POST", body: JSON.stringify(body) }); setChannels((current) => editingId ? current.map((channel) => channel.id === editingId ? data.channel : channel) : [...current, data.channel]); resetChannelForm(); } catch (err) { setChannelError(err instanceof Error ? err.message : "Failed to save WhatsApp channel."); } finally { setChannelSaving(false); } }
  async function toggleChannel(channel: Channel) { setChannelError(""); try { const data = await apiFetch<{ channel: Channel }>(`/api/whatsapp/channels/${channel.id}`, { method: "PATCH", body: JSON.stringify({ active: !channel.active }) }); setChannels((current) => current.map((item) => item.id === channel.id ? data.channel : item)); } catch (err) { setChannelError(err instanceof Error ? err.message : "Failed to update channel status."); } }

  return <main className="min-h-screen bg-slate-950 text-white"><div className="flex min-h-screen"><Sidebar /><section className="flex-1">
    <header className="border-b border-slate-800 px-6 py-5 md:px-10"><p className="text-sm font-medium text-slate-400">Workspace configuration</p><h1 className="mt-1 text-2xl font-bold">Settings</h1><p className="mt-1 text-sm text-slate-400">Configure business details, automation defaults, channels and optional AI fallback.</p></header>
    <div className="p-6 md:p-10"><div className="max-w-5xl space-y-6">
      {(error || message) && <div className={`rounded-xl border px-4 py-3 text-sm ${error ? "border-red-500/20 bg-red-500/10 text-red-400" : "border-emerald-500/20 bg-emerald-500/10 text-emerald-400"}`}>{error || message}</div>}
      <section className="rounded-xl border border-slate-800 bg-slate-900 p-6"><h2 className="text-lg font-semibold">Business</h2><p className="mt-1 text-sm text-slate-400">Your primary business contact details.</p><div className="mt-5 grid gap-4 md:grid-cols-2">{businessFields.map((field) => <label key={field.key} className="text-sm font-medium text-slate-300">{field.label}<input type={field.type} value={stringValue(settings[field.key])} onChange={(e) => update(field.key, e.target.value)} className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-white" placeholder={field.placeholder} /></label>)}</div></section>
      <section className="rounded-xl border border-slate-800 bg-slate-900 p-6"><h2 className="text-lg font-semibold">Automation</h2><p className="mt-1 text-sm text-slate-400">Rules are the default automation layer and do not require AI API calls.</p><div className="mt-5 space-y-4"><label className="flex items-center justify-between gap-4 rounded-xl border border-slate-800 bg-slate-950/50 p-4"><span><span className="block text-sm font-medium">Enable automation</span><span className="text-xs text-slate-500">Evaluate enabled rules for incoming messages.</span></span><input type="checkbox" checked={settings.automation_enabled} onChange={(e) => update("automation_enabled", e.target.checked)} /></label><label className="flex items-center justify-between gap-4 rounded-xl border border-slate-800 bg-slate-950/50 p-4"><span><span className="block text-sm font-medium">Auto-create leads</span><span className="text-xs text-slate-500">Allow create lead rules to create customer leads.</span></span><input type="checkbox" checked={settings.auto_create_leads} onChange={(e) => update("auto_create_leads", e.target.checked)} /></label><label className="block text-sm font-medium text-slate-300">Default response<textarea value={settings.default_response} onChange={(e) => update("default_response", e.target.value)} rows={3} className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm" /></label><label className="block text-sm font-medium text-slate-300">Human handoff message<textarea value={settings.human_handoff_message} onChange={(e) => update("human_handoff_message", e.target.value)} rows={3} className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm" /></label><label className="block text-sm font-medium text-slate-300">Default lead status<select value={settings.default_lead_status} onChange={(e) => update("default_lead_status", e.target.value)} className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm"><option value="new">New</option><option value="qualified">Qualified</option><option value="contacted">Contacted</option><option value="converted">Converted</option><option value="lost">Lost</option></select></label></div></section>
      <section className="rounded-xl border border-slate-800 bg-slate-900 p-6"><div className="flex flex-col gap-2 md:flex-row md:items-start md:justify-between"><div><h2 className="text-lg font-semibold">WhatsApp channels</h2><p className="mt-1 text-sm text-slate-400">Connect multiple WhatsApp Business numbers. Access and verify tokens are encrypted and never returned to this UI.</p></div><span className="rounded-full border border-slate-700 bg-slate-950 px-3 py-1 text-xs text-slate-400">{channels.length} channel{channels.length === 1 ? "" : "s"}</span></div>{channelError && <div className="mt-4 rounded-lg border border-red-500/20 bg-red-500/10 px-4 py-3 text-sm text-red-400">{channelError}<button type="button" onClick={() => void loadChannels()} className="ml-3 underline">Retry</button></div>}{channelsLoading ? <p className="mt-5 text-sm text-slate-500">Loading channels...</p> : channels.length === 0 ? <div className="mt-5 rounded-xl border border-dashed border-slate-700 p-5 text-sm text-slate-500">No WhatsApp channels connected yet. Add one below when Meta credentials are available.</div> : <div className="mt-5 space-y-3">{channels.map((channel) => <div key={channel.id} className="rounded-xl border border-slate-800 bg-slate-950/50 p-4"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-medium">{channel.name}</h3><span className={`rounded-full px-2.5 py-1 text-xs ${channel.active ? "bg-emerald-500/10 text-emerald-400" : "bg-slate-800 text-slate-500"}`}>{channel.active ? "Active" : "Inactive"}</span></div><p className="mt-2 text-xs text-slate-500">Phone number ID: {channel.phone_number_id} · API: {channel.graph_api_version}</p></div><div className="flex gap-2"><button type="button" onClick={() => editChannel(channel)} className="rounded-lg border border-slate-700 px-3 py-2 text-xs text-slate-300">Edit</button><button type="button" onClick={() => void toggleChannel(channel)} className="rounded-lg border border-slate-700 px-3 py-2 text-xs text-slate-300">{channel.active ? "Deactivate" : "Activate"}</button></div></div></div>)}</div>}
        <div className="mt-6 rounded-xl border border-slate-800 bg-slate-950 p-5"><div className="flex items-center justify-between"><div><h3 className="font-medium">{editingId ? "Edit channel" : "Add channel"}</h3><p className="mt-1 text-xs text-slate-500">{editingId ? "Leave token fields blank to keep existing encrypted credentials." : "Credentials are required for a new channel."}</p></div>{editingId && <button type="button" onClick={resetChannelForm} className="text-xs text-slate-400 underline">Cancel</button>}</div><div className="mt-4 grid gap-4 md:grid-cols-2">{[["name","Channel name","e.g. Camluk Main"],["whatsappBusinessAccountId","WhatsApp Business Account ID","e.g. 123456789"],["phoneNumberId","Phone number ID","e.g. 987654321"],["graphApiVersion","Graph API version","v23.0"]].map(([key,label,placeholder]) => <label key={key} className="text-sm font-medium text-slate-300">{label}<input value={channelForm[key as keyof typeof channelForm]} onChange={(e) => updateChannel(key as keyof typeof channelForm,e.target.value)} placeholder={placeholder} className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-white" /></label>)}<label className="text-sm font-medium text-slate-300">Access token<input type="password" autoComplete="new-password" value={channelForm.accessToken} onChange={(e) => updateChannel("accessToken",e.target.value)} placeholder={editingId ? "Leave blank to keep existing" : "Meta access token"} className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-white" /></label><label className="text-sm font-medium text-slate-300">Verify token<input type="password" autoComplete="new-password" value={channelForm.verifyToken} onChange={(e) => updateChannel("verifyToken",e.target.value)} placeholder={editingId ? "Leave blank to keep existing" : "Webhook verify token"} className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-white" /></label></div><button type="button" disabled={channelSaving} onClick={() => void saveChannel()} className="mt-4 rounded-lg bg-white px-4 py-2.5 text-sm font-semibold text-slate-950 disabled:opacity-50">{channelSaving ? "Saving..." : editingId ? "Save channel" : "Add channel"}</button></div>
      </section>
      <section className="rounded-xl border border-slate-800 bg-slate-900 p-6"><h2 className="text-lg font-semibold">AI fallback</h2><p className="mt-1 text-sm text-slate-400">Optional future fallback for messages that rules cannot confidently handle.</p><label className="mt-5 flex items-center justify-between gap-4 rounded-xl border border-slate-800 bg-slate-950/50 p-4"><span><span className="block text-sm font-medium">Enable AI fallback</span><span className="text-xs text-slate-500">Off by default to keep automation costs predictable.</span></span><input type="checkbox" checked={settings.ai_fallback_enabled} onChange={(e) => update("ai_fallback_enabled", e.target.checked)} /></label><div className="mt-4 rounded-xl border border-slate-800 bg-slate-950 p-4 text-sm text-slate-400">Provider: {settings.ai_provider || "None configured"} · API key: Not stored in business settings</div></section>
      <section className="rounded-xl border border-slate-800 bg-slate-900 p-6"><h2 className="text-lg font-semibold">Automation status</h2><p className="mt-1 text-sm text-slate-400">{loading ? "Loading..." : `${rules.filter((rule) => rule.enabled).length} enabled of ${rules.length} rules`}</p></section>
      <button disabled={saving || loading} type="button" onClick={() => void saveSettings()} className="rounded-lg bg-white px-5 py-2.5 text-sm font-semibold text-slate-950 disabled:opacity-50">{saving ? "Saving..." : "Save settings"}</button>
    </div></div>
  </section></div></main>;
}
