"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import Sidebar from "../../components/Sidebar";
import { apiFetch } from "../../lib/api";

type Lead = { id: string; customerId: string; customerName: string; phone: string; email: string; serviceCategory: string | null; status: string; notes: string; createdAt: string; updatedAt: string };
type Pagination = { page: number; limit: number; total: number; totalPages: number };
type Summary = { total: number; new: number; contacted: number; qualified: number; converted: number; lost: number };
function formatServiceCategory(category: string | null) { if (!category) return "Not specified"; return category.split("-").map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(" "); }
function statusClasses(status: string) { switch (status) { case "new": return "bg-blue-500/10 text-blue-400 border-blue-500/20"; case "contacted": return "bg-yellow-500/10 text-yellow-400 border-yellow-500/20"; case "qualified": return "bg-purple-500/10 text-purple-400 border-purple-500/20"; case "converted": return "bg-green-500/10 text-green-400 border-green-500/20"; case "lost": return "bg-red-500/10 text-red-400 border-red-500/20"; default: return "bg-slate-500/10 text-slate-400 border-slate-500/20"; } }
function formatStatus(status: string) { return status.charAt(0).toUpperCase() + status.slice(1); }

export default function LeadsPage() {
  const [leads, setLeads] = useState<Lead[]>([]); const [page, setPage] = useState(1); const [pagination, setPagination] = useState<Pagination>({ page: 1, limit: 5, total: 0, totalPages: 0 }); const [summary, setSummary] = useState<Summary>({ total: 0, new: 0, contacted: 0, qualified: 0, converted: 0, lost: 0 }); const [status, setStatus] = useState(""); const [service, setService] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const services = ["web-development", "business-software", "ai-automation", "cloud-deployment", "general"];

  useEffect(() => { setLoading(true); setError(""); const params = new URLSearchParams({ page: String(page), limit: "5" }); if (status) params.set("status", status); if (service) params.set("service", service); apiFetch<{ leads: Lead[]; pagination: Pagination; summary: Summary }>(`/api/leads?${params}`).then(data => { setLeads(data.leads || []); setPagination(data.pagination); setSummary(data.summary); }).catch(error => { console.error(error); setError("Unable to load leads. Please try again."); }).finally(() => setLoading(false)); }, [page, status, service]);
  function updateFilter(setter: (value: string) => void, value: string) { setPage(1); setter(value); }

  return <main className="min-h-screen bg-slate-950 text-white"><div className="flex min-h-screen"><Sidebar /><section className="flex-1"><header className="border-b border-slate-800 px-6 py-5 md:px-10"><h1 className="text-2xl font-semibold">Leads</h1><p className="mt-1 text-sm text-slate-400">Track and manage potential customers generated from conversations.</p></header><div className="p-6 md:p-10">
    <div className="mb-6 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><h2 className="text-lg font-semibold">Lead pipeline</h2><p className="mt-1 text-sm text-slate-400">5 leads per page.</p></div><div className="flex flex-col gap-2 sm:flex-row"><select value={status} onChange={e => updateFilter(setStatus, e.target.value)} className="rounded-lg border border-slate-700 bg-slate-900 px-4 py-2 text-sm text-slate-300 outline-none"><option value="">All statuses</option><option value="new">New</option><option value="contacted">Contacted</option><option value="qualified">Qualified</option><option value="converted">Converted</option><option value="lost">Lost</option></select><select value={service} onChange={e => updateFilter(setService, e.target.value)} className="rounded-lg border border-slate-700 bg-slate-900 px-4 py-2 text-sm text-slate-300 outline-none"><option value="">All services</option>{services.map(value => <option key={value} value={value}>{formatServiceCategory(value)}</option>)}</select></div></div>
    <div className="mb-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{[["Total Leads", summary.total], ["New", summary.new], ["Contacted", summary.contacted], ["Qualified", summary.qualified], ["Converted", summary.converted]].map(([label, value]) => <div key={String(label)} className="rounded-xl border border-slate-800 bg-slate-900 p-5"><p className="text-sm text-slate-400">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div>)}</div>
    {loading ? <div className="rounded-xl border border-dashed border-slate-700 bg-slate-900 p-10 text-center text-sm text-slate-400">Loading leads...</div> : error ? <div className="rounded-xl border border-red-900 bg-red-950/30 p-10 text-center text-sm text-red-400">{error}</div> : leads.length === 0 ? <div className="rounded-xl border border-dashed border-slate-700 bg-slate-900 p-10 text-center text-sm text-slate-400">No leads match the selected filters.</div> : <div className="overflow-hidden rounded-xl border border-slate-800 bg-slate-900"><div className="overflow-x-auto"><table className="w-full text-left"><thead className="border-b border-slate-800 bg-slate-950/50"><tr><th className="px-6 py-4 text-xs font-medium uppercase tracking-wide text-slate-400">Customer</th><th className="px-6 py-4 text-xs font-medium uppercase tracking-wide text-slate-400">Service</th><th className="px-6 py-4 text-xs font-medium uppercase tracking-wide text-slate-400">Status</th><th className="px-6 py-4 text-xs font-medium uppercase tracking-wide text-slate-400">Notes</th><th className="px-6 py-4 text-xs font-medium uppercase tracking-wide text-slate-400">Created</th><th className="px-6 py-4 text-xs font-medium uppercase tracking-wide text-slate-400">Action</th></tr></thead><tbody>{leads.map(lead => <tr key={lead.id} className="border-b border-slate-800 last:border-0 hover:bg-slate-800/30"><td className="px-6 py-4"><p className="font-medium text-white">{lead.customerName}</p><p className="mt-1 text-xs text-slate-500">{lead.phone}</p></td><td className="px-6 py-4 text-sm text-slate-300">{formatServiceCategory(lead.serviceCategory)}</td><td className="px-6 py-4"><span className={`inline-flex rounded-full border px-3 py-1 text-xs font-medium ${statusClasses(lead.status)}`}>{formatStatus(lead.status)}</span></td><td className="max-w-xs px-6 py-4 text-sm text-slate-400"><p className="truncate">{lead.notes || "—"}</p></td><td className="px-6 py-4 text-sm text-slate-400">{new Date(lead.createdAt).toLocaleDateString()}</td><td className="px-6 py-4"><Link href={`/leads/${lead.id}`} className="inline-flex rounded-lg border border-slate-700 px-3 py-2 text-xs font-medium text-white hover:bg-slate-800">Open</Link></td></tr>)}</tbody></table></div></div>}
    {!loading && !error && pagination.totalPages > 1 && <div className="mt-5 flex items-center justify-between rounded-xl border border-slate-800 bg-slate-900 px-4 py-3"><p className="text-xs text-slate-500">Page {pagination.page} of {pagination.totalPages} · {pagination.total} matching</p><div className="flex gap-2"><button disabled={page === 1} onClick={() => setPage(p => p - 1)} className="rounded-lg border border-slate-700 px-3 py-2 text-xs disabled:opacity-40">Previous</button><button disabled={page >= pagination.totalPages} onClick={() => setPage(p => p + 1)} className="rounded-lg border border-slate-700 px-3 py-2 text-xs disabled:opacity-40">Next</button></div></div>}
  </div></section></div></main>;
}
